// 마인크래프트 아이템의 실제 텍스처를 모사하지 않는, 완전히 새로 디자인한
// 8x8 픽셀 아이콘 시스템. 유형(모양) + 재질(색) 조합으로 306개 항목을 커버한다.
// '.' = 투명, 'A' = 기본색(fill), 'B' = 진한 음영, 'C' = 밝은 하이라이트, 'D' = 보조색(손잡이 등)

export type Shape = string[];

export const SHAPES: Record<string, Shape> = {
  sword: [
    '...A....',
    '..AB....',
    '.AB.....',
    'AB......',
    '.DA.....',
    '..D.....',
    '..D.....',
    '.DDD....',
  ],
  pickaxe: [
    '.AAAAA..',
    'AABBBAA.',
    '.....D..',
    '.....D..',
    '....D...',
    '....D...',
    '...D....',
    '...D....',
  ],
  axe: [
    '..AAA...',
    '.AABBA..',
    '.ABBBA..',
    '..D.....',
    '..D.....',
    '.D......',
    '.D......',
    'D.......',
  ],
  shovel: [
    '..AAA...',
    '.ABBBA..',
    '..ABA...',
    '...D....',
    '...D....',
    '...D....',
    '..D.....',
    '..D.....',
  ],
  hoe: [
    '..AAAA..',
    '.ABBBBA.',
    '.....D..',
    '....D...',
    '....D...',
    '...D....',
    '...D....',
    '..D.....',
  ],
  helmet: [
    '..AAAA..',
    '.ABBBBA.',
    'ABBBBBBA',
    'ABBBBBBA',
    'A......A',
    '........',
    '........',
    '........',
  ],
  chestplate: [
    'A..AA..A',
    'ABBAABBA',
    'ABBBBBBA',
    'ABBBBBBA',
    'ABBBBBBA',
    '.ABBBBA.',
    '........',
    '........',
  ],
  leggings: [
    'AAAAAAAA',
    'ABBBBBBA',
    'ABBBBBBA',
    'ABB..BBA',
    'ABB..BBA',
    'ABB..BBA',
    'ABB..BBA',
    '........',
  ],
  boots: [
    '..AAA...',
    '..ABA...',
    '..ABA...',
    '..ABA...',
    '..ABA...',
    '.AABBAA.',
    'AABBBBAA',
    '........',
  ],
  ingot: [
    '........',
    '.AAAAAA.',
    'ABBBBBBA',
    'ABBCCBBA',
    'ABBBBBBA',
    '.AAAAAA.',
    '........',
    '........',
  ],
  gem: [
    '...AA...',
    '..ABBA..',
    '.ABCCBA.',
    'ABBCCBBA',
    '.ABBBBA.',
    '..ABBA..',
    '...AA...',
    '........',
  ],
  ore_block: [
    'AAAAAAAA',
    'ABB.B.BA',
    'A.BBB..A',
    'AB..B.BA',
    'ABB.BB.A',
    'A.B..B.A',
    'AB.BB..A',
    'AAAAAAAA',
  ],
  block: [
    'AAAAAAAA',
    'ACCBBCCA',
    'ACBBBBCA',
    'ACBBBBCA',
    'ACBBBBCA',
    'ACBBBBCA',
    'ACCBBCCA',
    'AAAAAAAA',
  ],
  log: [
    '.AAAAAA.',
    'ABBBBBBA',
    'ABCCCCBA',
    'ABC..CBA',
    'ABC..CBA',
    'ABCCCCBA',
    'ABBBBBBA',
    '.AAAAAA.',
  ],
  plank: [
    'AAAAAAAA',
    'ABBBBBBA',
    '........',
    'AAAAAAAA',
    'ABBBBBBA',
    '........',
    'AAAAAAAA',
    'ABBBBBBA',
  ],
  plant: [
    '........',
    '...A....',
    '..ABA...',
    '.ABBBA..',
    '...D....',
    '...D....',
    '..DDD...',
    '........',
  ],
  crop_top: [
    '........',
    '..A..A..',
    '.ABAABA.',
    '..ABBA..',
    '...DD...',
    '...D....',
    '..DDD...',
    '........',
  ],
  creature: [
    '.AAAAAA.',
    'AABBBBAA',
    'ABB..BBA',
    'ABBBBBBA',
    'AABBBBAA',
    '.AA..AA.',
    '.D....D.',
    '........',
  ],
  hostile: [
    '.AAAAAA.',
    'AABBBBAA',
    'ABDBBDBA',
    'ABBBBBBA',
    'ABBDDBBA',
    '.AABBAA.',
    '.D....D.',
    '........',
  ],
  boss: [
    'A.A..A.A',
    '.AAAAAA.',
    'ABBBBBBA',
    'ABDDDDBA',
    'ABBBBBBA',
    '.ABBBBA.',
    '..AAAA..',
    '........',
  ],
  potion: [
    '..AA....',
    '..AA....',
    '.AAAA...',
    'ABBBBA..',
    'ABBBBA..',
    'ABBBBA..',
    '.AAAA...',
    '........',
  ],
  food: [
    '..AA....',
    '.ABBA...',
    'ABBBBA..',
    'ABBBBA..',
    'ABBBBA..',
    '.ABBA...',
    '..DD....',
    '........',
  ],
  book: [
    'AAAAAAA.',
    'ABBBBBA.',
    'ABDBBDA.',
    'ABBBBBA.',
    'ABDBBDA.',
    'ABBBBBA.',
    'AAAAAAA.',
    '........',
  ],
  redstone: [
    '........',
    '.AAAAAA.',
    'ABBBBBBA',
    'ABBDDBBA',
    'ABBDDBBA',
    'ABBBBBBA',
    '.AAAAAA.',
    '........',
  ],
  bow: [
    'AA......',
    'A.A.....',
    'A..A....',
    'D...A...',
    'D....A..',
    'A...A...',
    'A.A.....',
    'AA......',
  ],
  shield: [
    '.AAAAAA.',
    'ABBBBBBA',
    'ABBDDBBA',
    'ABBDDBBA',
    '.ABBBBA.',
    '..ABBA..',
    '...AA...',
    '........',
  ],
  wool_ball: [
    '..AAAA..',
    '.AABBAA.',
    'AABBBBAA',
    'AABBBBAA',
    'AABBBBAA',
    '.AABBAA.',
    '..AAAA..',
    '........',
  ],
  egg: [
    '..AAAA..',
    '.ABBBBA.',
    'ABBBBBBA',
    'ABBBBBBA',
    'ABBBBBBA',
    '.ABBBBA.',
    '..AAAA..',
    '........',
  ],
  cart: [
    'A......A',
    'AA....AA',
    'ABBBBBBA',
    'ABBBBBBA',
    'ABBBBBBA',
    '.A....A.',
    '.OO..OO.',
    '........',
  ],
  spark: [
    '...A....',
    '...A....',
    '.A.A.A..',
    '..AAA...',
    'A..A..A.',
    '.A.A.A..',
    '...A....',
    '........',
  ],
  generic: [
    '.AAAAAA.',
    'ABBBBBBA',
    'ABBBBBBA',
    'ABBBBBBA',
    'ABBBBBBA',
    'ABBBBBBA',
    'ABBBBBBA',
    '.AAAAAA.',
  ],
};

// id 패턴 -> 모양
const SHAPE_RULES: [RegExp, string][] = [
  [/_sword$/, 'sword'],
  [/_pickaxe$/, 'pickaxe'],
  [/_axe$/, 'axe'],
  [/_shovel$/, 'shovel'],
  [/_hoe$/, 'hoe'],
  [/_helmet$/, 'helmet'],
  [/_chestplate$/, 'chestplate'],
  [/_leggings$/, 'leggings'],
  [/_boots$/, 'boots'],
  [/_ingot$/, 'ingot'],
  [/^(diamond|emerald|lapis_lazuli|amethyst)$/, 'gem'],
  [/_ore$/, 'ore_block'],
  [/_log$/, 'log'],
  [/_planks?$/, 'plank'],
  [/^(wheat|carrot|potato|beetroot|sugar_cane|nether_wart|bamboo|kelp|torchflower)$/, 'plant'],
  [/^(melon_block|pumpkin|cocoa_beans|sweet_berries|glow_berries)$/, 'crop_top'],
  [/^(potion_|potion$)/, 'potion'],
  [/^(bow|crossbow)$/, 'bow'],
  [/^shield$/, 'shield'],
  [/^book|enchanted_book$/, 'book'],
  [/^(redstone|redstone_torch|repeater|comparator|observer|dispenser|dropper|note_block|target_block|daylight_detector|detector_rail|redstone_lamp)$/, 'redstone'],
  [/^(wool|carpet|dye|banner|bed)$/, 'wool_ball'],
  [/^(minecart|boat|rail|powered_rail)$/, 'cart'],
  [/^(ench_)/, 'spark'],
  [/^(apple|golden_apple|bread|cooked_beef|cooked_porkchop|cooked_chicken|golden_carrot|cake|cookie|pumpkin_pie|honey_bottle|melon|cod|salmon)$/, 'food'],
];

function pickShape(item: { id: string; category: string; subcategory: string }): Shape {
  for (const [re, shape] of SHAPE_RULES) {
    if (re.test(item.id)) return SHAPES[shape];
  }
  if (item.category === '몹') {
    if (item.subcategory === '보스') return SHAPES.boss;
    if (item.subcategory === '적대적') return SHAPES.hostile;
    return SHAPES.creature;
  }
  if (item.category === '작물') return SHAPES.plant;
  if (item.category === '블록') return SHAPES.block;
  if (item.category === '기타') return SHAPES.spark;
  return SHAPES.generic;
}

// id에 포함된 재질 키워드 -> 색상(기본색A, 음영B, 하이라이트C, 보조색D)
const COLOR_RULES: [RegExp, { a: string; b: string; c: string; d: string }][] = [
  [/diamond/, { a: '#7de3e8', b: '#3fa9ae', c: '#d9fbfc', d: '#8a5a3b' }],
  [/gold|golden/, { a: '#ffd94a', b: '#c99b1f', c: '#fff3b0', d: '#8a5a3b' }],
  [/iron/, { a: '#d8d8d8', b: '#9a9a9a', c: '#f4f4f4', d: '#8a5a3b' }],
  [/emerald/, { a: '#3ecf6b', b: '#1f8a45', c: '#a9f5c0', d: '#8a5a3b' }],
  [/netherite/, { a: '#4a4048', b: '#241f24', c: '#6e5f68', d: '#3a3038' }],
  [/redstone/, { a: '#e23c3c', b: '#8f1f1f', c: '#ff8080', d: '#4a1414' }],
  [/lapis/, { a: '#3b6fd6', b: '#1f3f8a', c: '#9db8f2', d: '#8a5a3b' }],
  [/copper/, { a: '#e08a4f', b: '#a85a2a', c: '#f5c194', d: '#8a5a3b' }],
  [/coal/, { a: '#3a3a3a', b: '#161616', c: '#5c5c5c', d: '#8a5a3b' }],
  [/obsidian/, { a: '#3d2a5c', b: '#1c0f30', c: '#6b4f96', d: '#1c0f30' }],
  [/^stone|cobblestone|granite|deepslate|andesite|diorite/, { a: '#9a9a9a', b: '#6b6b6b', c: '#c4c4c4', d: '#6b6b6b' }],
  [/leather/, { a: '#a56a3a', b: '#6e4423', c: '#c98c5a', d: '#6e4423' }],
  [/wolf|wool|sheep/, { a: '#f2f2f2', b: '#c9c9c9', c: '#ffffff', d: '#c9c9c9' }],
  [/zombie|creeper|husk/, { a: '#4fae5c', b: '#2c6e35', c: '#8fd89b', d: '#0d0d0d' }],
  [/skeleton|bone|wither_skeleton|stray/, { a: '#e6e2d3', b: '#b3ae9c', c: '#ffffff', d: '#0d0d0d' }],
  [/ender/, { a: '#3d2a5c', b: '#1c0f30', c: '#8a5fd6', d: '#0d0d0d' }],
  [/piglin|hoglin|pig\b|pig$/, { a: '#f0a6b8', b: '#c76e8a', c: '#ffd4e0', d: '#8a5a3b' }],
  [/cow|mooshroom/, { a: '#8a5a3b', b: '#5c3a24', c: '#c99b6a', d: '#f2f2f2' }],
  [/chicken/, { a: '#f2f2f2', b: '#c9c9c9', c: '#ffffff', d: '#e0a030' }],
  [/sheep|llama|goat/, { a: '#e8e2d0', b: '#b8b09a', c: '#ffffff', d: '#8a5a3b' }],
  [/wheat|hay/, { a: '#e0c34a', b: '#a88f2a', c: '#f5e3a0', d: '#4fae5c' }],
  [/carrot/, { a: '#e8862a', b: '#a85a15', c: '#f7b56a', d: '#4fae5c' }],
  [/potato/, { a: '#c99b5a', b: '#8a6530', c: '#e0c090', d: '#4fae5c' }],
  [/melon/, { a: '#4fae5c', b: '#2c6e35', c: '#e0405c', d: '#2c6e35' }],
  [/pumpkin/, { a: '#e07a1e', b: '#a8540f', c: '#f7ae6a', d: '#4fae5c' }],
  [/oak|acacia/, { a: '#b58a52', b: '#7a5a30', c: '#d9b483', d: '#4fae5c' }],
  [/spruce|dark_oak/, { a: '#6e4a2c', b: '#4a2f1a', c: '#96703f', d: '#2c6e35' }],
  [/birch/, { a: '#e0d0a0', b: '#b3a06a', c: '#f5eecb', d: '#4fae5c' }],
  [/jungle|mangrove/, { a: '#8a5a3b', b: '#5c3a24', c: '#c99b6a', d: '#2c6e35' }],
  [/cherry|red_poplar/, { a: '#f2a0c0', b: '#d66e9a', c: '#ffd0e5', d: '#8a5a3b' }],
  [/orange_poplar/, { a: '#f0a84a', b: '#c9801f', c: '#ffd8a0', d: '#8a5a3b' }],
  [/yellow_poplar/, { a: '#f0d84a', b: '#c9ae1f', c: '#ffefa0', d: '#8a5a3b' }],
  [/water|drowned|dolphin|cod|salmon|squid|fish|guardian|turtle|axolotl/, { a: '#3e9bd6', b: '#1f5f8a', c: '#a0d8f5', d: '#1f5f8a' }],
  [/nether|blaze|ghast|magma|hoglin|strider/, { a: '#e06a2a', b: '#a8420f', c: '#f7a56a', d: '#3a1f14' }],
  [/potion|witch/, { a: '#b03ecf', b: '#7a1f96', c: '#e0a0f5', d: '#4a1f5c' }],
];

const CATEGORY_COLOR: Record<string, { a: string; b: string; c: string; d: string }> = {
  블록: { a: '#9a9a9a', b: '#6b6b6b', c: '#c4c4c4', d: '#6b6b6b' },
  아이템: { a: '#8a97a8', b: '#5c6a7a', c: '#c4cfd9', d: '#5c6a7a' },
  몹: { a: '#7a9a5c', b: '#4a6e35', c: '#a8c98a', d: '#0d0d0d' },
  작물: { a: '#6ab34a', b: '#3f7a2a', c: '#a0d989', d: '#8a5a3b' },
  기타: { a: '#7a6ad6', b: '#4a3f96', c: '#b3a8f2', d: '#4a3f96' },
};

function pickColor(item: { id: string; category: string }) {
  for (const [re, color] of COLOR_RULES) {
    if (re.test(item.id)) return color;
  }
  return CATEGORY_COLOR[item.category] ?? CATEGORY_COLOR['아이템'];
}

export function getIcon(item: { id: string; category: string; subcategory: string }) {
  return { shape: pickShape(item), color: pickColor(item) };
}
